<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-PO0RLHQF" failures="1" tests="9" name="Default test" time="81.623" errors="0" timestamp="2022-09-27T00:14:10 CDT">
  <testcase classname="com.DSAlgo.TestCase.RegistrationPageTest" name="registration_with_existuserTest" time="21.853">
    <failure type="java.lang.AssertionError" message="expected [This user already exist,try with other one] but found [password_mismatch:The two password fields didn’t match.]">
      <![CDATA[java.lang.AssertionError: expected [This user already exist,try with other one] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.DSAlgo.TestCase.RegistrationPageTest.registration_with_existuserTest(RegistrationPageTest.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- registration_with_existuserTest -->
  <testcase classname="com.DSAlgo.TestCase.RegistrationPageTest" name="registrationTest" time="7.906"/>
  <testcase classname="com.DSAlgo.TestCase.RegistrationPageTest" name="registrationTest" time="7.792"/>
  <testcase classname="com.DSAlgo.TestCase.RegistrationPageTest" name="registrationTest" time="7.695"/>
  <testcase classname="com.DSAlgo.TestCase.RegistrationPageTest" name="registrationTest" time="2.767"/>
  <testcase classname="com.DSAlgo.TestCase.RegistrationPageTest" name="registrationTest" time="2.677"/>
  <testcase classname="com.DSAlgo.TestCase.RegistrationPageTest" name="registrationTest" time="2.749"/>
  <testcase classname="com.DSAlgo.TestCase.RegistrationPageTest" name="registrationTest" time="2.832"/>
  <testcase classname="com.DSAlgo.TestCase.RegistrationPageTest" name="registrationTest" time="3.054"/>
</testsuite> <!-- Default test -->
